/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connectivity.Dbmanager;
import connectivity.QueryManager;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.WinkelApplication;
import model.Order;
import model.Product;

/**
 *
 * @author davida7
 */
public class OrderList extends javax.swing.JPanel {

    /**
     * Creates new form OrderList
     */
    
    private QueryManager queryManager;
    
    public OrderList() {
        initComponents();
        
        List<Order> orders = WinkelApplication.getQueryManager().getOrder();
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        for (Order order : orders) {
            model.addRow(new Object[]{new Integer(order.getProductId()),
                        order.getOrderId(),
                        order.getAmount()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTerug = new javax.swing.JButton();
        btnVerwijder = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_id", "Order_id", "Aantal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnTerug.setText("Terug");
        btnTerug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerugActionPerformed(evt);
            }
        });

        btnVerwijder.setText("Verwijder");
        btnVerwijder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnVerwijder)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnTerug)
                .add(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 302, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnTerug)
                    .add(btnVerwijder))
                .add(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerugActionPerformed
        // TODO add your handling code here:
        WinkelApplication.getInstance().showPanel(new view.MedewerkerPanel());
    }//GEN-LAST:event_btnTerugActionPerformed

    private void btnVerwijderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderActionPerformed
        // TODO add your handling code here:
        queryManager = new QueryManager(new Dbmanager());

        int row = jTable1.getSelectedRow();
        
        int product_id = (Integer) (jTable1.getValueAt(row, 0));
        int order_id = (Integer) (jTable1.getValueAt(row, 1));
        int amount = (Integer) jTable1.getValueAt(row, 2);
        
        queryManager.deleteOrder(product_id, order_id, amount);
        WinkelApplication.getInstance().showPanel(new view.OrderList());
        
    }//GEN-LAST:event_btnVerwijderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerug;
    private javax.swing.JButton btnVerwijder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
